POST http://localhost:59111/register/
Content-Type:application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}
###

POST http://localhost:59111/login/
Content-Type:application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}
###

GET http://localhost:59111/user/tweets/feed/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc5NTA3OTI1fQ.QPDhPI2YFiIyahjBQwmLdPjYFga6gYYkI8o2Hhorh0I
###
GET http://localhost:59111/user/following/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc5NTA3OTI1fQ.QPDhPI2YFiIyahjBQwmLdPjYFga6gYYkI8o2Hhorh0I
###
GET http://localhost:59111/user/followers/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc5NTA3OTI1fQ.QPDhPI2YFiIyahjBQwmLdPjYFga6gYYkI8o2Hhorh0I
###
GET http://localhost:59111/tweets/1/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc5NTA3OTI1fQ.QPDhPI2YFiIyahjBQwmLdPjYFga6gYYkI8o2Hhorh0I
###
GET http://localhost:59111/tweets/1/likes/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc5NTA3OTI1fQ.QPDhPI2YFiIyahjBQwmLdPjYFga6gYYkI8o2Hhorh0I
###
GET http://localhost:59111/tweets/1/replies/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc5NTA3OTI1fQ.QPDhPI2YFiIyahjBQwmLdPjYFga6gYYkI8o2Hhorh0I
###
GET http://localhost:59111/user/tweets/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc5NTA3OTI1fQ.QPDhPI2YFiIyahjBQwmLdPjYFga6gYYkI8o2Hhorh0I
###
POST http://localhost:59111/user/tweets/
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc5NTA3OTI1fQ.QPDhPI2YFiIyahjBQwmLdPjYFga6gYYkI8o2Hhorh0I

{
   "tweet": "The Mornings..."
}
###
DELETE http://localhost:59111/tweets/22/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc5NTA3OTI1fQ.QPDhPI2YFiIyahjBQwmLdPjYFga6gYYkI8o2Hhorh0I
###